- _app/js/sanity.js
- _app/js/util/sanity-client.js
Added Client.js and made santiy.js under _app
> Made client.js and added sanity.js

- _studio/schemas/documents/author.js
> Bug: Fix typo in author

- _app/js/main.js
- _app/js/modules/book-list.js
> Rendered booklist in DOM

- _app/css/base.css
- _app/css/main.css
> Feature: Made base grid for body

- _app/css/main.css
- _app/css/modules/header.css
- _app/css/variables.css
- index.html
> Made the header

- _studio/schemas/documents/author.js
- _studio/schemas/documents/book.js
> Feature: Added Alt text portion to author and book

- _app/css/main.css
- _app/css/modules/book-card.css
- _app/css/modules/header.css
> Feature: Add styling in book-card

- _app/css/base.css
- _app/css/fonts.css
- _app/css/main.css
- _app/css/modules/header.css
- index.html
> Styled and added font to header

- _app/css/main.css
- _app/css/modules/footer.css
- index.html
> created the footer

- _app/css/main.css
- _app/css/modules/book-search.css
- _app/js/main.js
- _app/js/modules/book-search.js
- index.html
> Feature: Add searchmodule

- meeting-notes.txt
Added Meetingnotes from 2nd sprint
> Feature: Meeting-notes 2023-03-31

- _app/js/modules/author-list.js
Added author names and minor bug fix #46
> Bug: Added author names and minor bug fix

- _app/js/modules/book-list.js
Added name query for author name in booklist #52
> Feature: Added query

- _app/css/base.css
- _app/css/fonts.css
- _app/css/modules/footer.css
- _app/css/modules/header.css
- _app/css/variables.css
> added variables

- _app/css/modules/book-search.css
- _app/js/modules/book-search.js
- index.html
> Feature: add book-search styling and button

- _app/js/modules/book-search.js
> Bug: Added firstName to query

- _app/js/modules/author-list.js
- _app/js/modules/book-list.js
> Feature: Added author-book and alt text for the images

- author/index.html
- index.html
> Feature: Added SEO and metatags

- _app/css/base.css
- _app/css/modules/header.css
- index.html
> added styling to the menu

- _app/js/main.js
- _app/js/modules/book-list.js
- index.html
> Feature: Add search and debounce to book-list

- _app/css/base.css
- _app/css/main.css
- _app/css/modules/book-card.css
- _app/css/modules/book-list.css
- _app/css/modules/book-search.css
- _app/js/modules/book-list.js
- index.html
> Feature: Added styling to search and book-list

- meeting-notes.txt
> Added meeting notes 2023/04/11

- _app/css/main.css
- _app/css/modules/author-card.css
- _app/css/variables.css
- _app/js/modules/author-list.js
- author/index.html
Fix #47 
Added styling to author page
> Feature: Styled the Author page according to prototype

- _app/css/modules/header.css
- _app/css/variables.css
> added media query to header

- _studio/sanity.config.js
- _studio/schemas/documents/aboutus.js
- _studio/schemas/documents/author.js
- _studio/schemas/schemas.js
- _studio/structure/book.js
- _studio/structure/information.js
> Feature: singleton schema structure

- _app/css/modules/author-card.css
- _app/css/modules/book-card.css
- _app/css/variables.css
- _app/js/modules/author-list.js
- _app/js/modules/book-list.js
> Feature:Minor style changes in book card and fonts

- readme.md
> Added link to Sanity

- author/index.html
- meeting-notes.txt
> Bug: Fixed author-links and changes in meeting notes

- _app/js/modules/book-list.js
- readme.md
> Bug: Minor bugfixes

- readme.md
> Update readme to contain github project
